### ISSUE TITLE
[Bug] SharedRunnerBase is basically impossible to define

### ISSUE THREAD

**Issue by sbtoonz** [CorrM/CleanCheat#2]
When attemping to use CC as a part of my projects I spend 2-3 days fighting with the IDE 

It will always complain that shareddatastruct is already declared 

there is no way out of this circle that is easy

the only way  to use your project is to start with your entire solution and replace files inside the example

otherwise it fails to compile for various reasons

SharedDataStruct already declared
Cannot Convert RunnerType<Ut8> to TT

**Comment by CorrM** [comment]
Sorry for the delay on the response, i was so busy last days.

Are you sure about your includes ?
![image](https://user-images.githubusercontent.com/5868825/198878014-9dd2b2ff-8583-4977-aa27-3f6c5e2feb1c.png)

If you can upload simple project  that have the problem will help me fix if there a bug.

**Comment by CorrM** [comment]
> Hate to break it to ya bud, but he's not gonna be worth much help. "check pins"
> 
> The only reason he made this is because people in the discord server complain about the same thing over and over again.
> 
> In all reality you could do all of this yourself and a whole heck of a lot cleaner to. The "runner" also isnt 100% crash proof as there is still gonna be occasions when memory accessed is no longer valid.

I love this project and i maintain it, so if there a bug i will fix it. I just was busy last days

**Comment by sbtoonz** [comment]
Sure

I will try to illustrate the problem in code and share with you

**Comment by sbtoonz** [comment]
after discussion with Corr it appears my use case was wrong

**Comment by xCENTx** [comment]
> > Hate to break it to ya bud, but he's not gonna be worth much help. "check pins"
> > The only reason he made this is because people in the discord server complain about the same thing over and over again.
> > In all reality you could do all of this yourself and a whole heck of a lot cleaner to. The "runner" also isnt 100% crash proof as there is still gonna be occasions when memory accessed is no longer valid.
> 
> I love this project and i maintain it, so if there a bug i will fix it. I just was busy last days.
> 
> > In all reality you could do all of this yourself and a whole heck of a lot cleaner to. The "runner" also isnt 100% crash proof as there is still gonna be occasions when memory accessed is no longer valid.
> 
> Can you explain more?

This is why you have since closed issues correct? Because you would love to maintain your project and provide a way for your userbase to highlight these issues?

It's good to see you fixed the issue nonetheless. CheatGear is a pretty cool project when it works
